//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zCush.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int AddressId { get; set; }
        public int ContactId { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public int CustomerTypeId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
