//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zCush.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLineItems = new HashSet<OrderLineItem>();
        }
    
        public int ID { get; set; }
        public string PONumber { get; set; }
        public int CustomerId { get; set; }
        public int AddressId { get; set; }
        public System.DateTime PODate { get; set; }
        public int OrderStatusId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
    }
}
