//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zCush.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_AmazonWarehouse
    {
        public int ID { get; set; }
        public string Identifier { get; set; }
        public string SanCode { get; set; }
        public string CartonQtySanCode { get; set; }
        public string Name { get; set; }
        public int AddressId { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
